development:
  adapter: postgresql
  encoding: unicode
  database: insta-vacation_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: insta-vacation_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: insta-vacation_production
  pool: 5
